<?php
$titolo = [];
$descrizione = [];

$titolo["cinopiteco"] = "Cinopiteco";
$descrizione["cinopiteco"] = "Il cinopiteco (Macaca nigra) è una scimmia del Vecchio Mondo appartenente alla sottofamiglia dei Cercopitecini. Differisce dalle altre specie di macachi per il caratteristico colore nero, il maschio è più grande dell'esemplare femmina (con una lunghezza di 65 cm e un peso di 10 kg). Ha la coda molto corta e sulla testa ha una cresta di lunghi peli che normalmente restato appiattiti e che si rizzano quando l'animale è eccitato. Questa specie si riunisce in gruppi misti di più di 100 individui. Solitamente vive nelle foreste e conduce un'esistenza tranquilla cercando di non dare nell'occhio. Nel 2011, il fotografo naturalista David Slater, durante un viaggio in Indonesia, stava scattando delle fotografie ad una femmina di Macaca nigra; durante la preparazione dell'attrezzatura, il macaco si è impossessato della macchina fotografica, scattando diverse fotografie. Alcune erano sfocate, mentre altre erano foto tecnicamente perfette, ribattezzate da Slater 'monkey's selfie'.";

$titolo["aironecenerino"] = "Airone cenerino";
$descrizione["aironecenerino"] = "L'airone cenerino (Ardea cinerea Linnaeus, 1758) è un uccello appartenente alla famiglia Ardeidae. Originario delle regioni temperate del Vecchio Mondo, oltre che dell'Africa, è la specie di airone che si spinge più a nord, tanto che in estate è facile incontrarlo lungo le coste norvegesi, ben oltre il circolo polare artico. Da adulto arriva ad una statura di 90-98 centimetri e un peso compreso tra 1020 e 2073 grammi. L'apertura alare può facilmente raggiungere 1,70 metri. Le sue piume sono grigiastre nella parte superiore e bianche in quella inferiore. Le zampe e il becco sono gialli. L'adulto ha piume nere sul collo e un ciuffo nucale nero molto evidente che si diparte dalla sommità posteriore e superiore dell'occhio. Nei giovani predomina il colore grigio.";

$titolo["anatramuta"] = "Anatra muta";
$descrizione["anatramuta"] = "L'anatra muta, detta anche anatra muschiata (Cairina Moschata) è un uccello appartenente alla famiglia degli Anatidi, molto diffusa nel Sud America in particolar modo in Messico, Nicaragua, Guatemala e Costa Rica. Giunta in Europa nella varietà domestica, è rinomata particolarmente per la produzione delle carni. L'anatra muta ha un carattere piuttosto mite e pacato, estremamente docile e domestica nei confronti dell'uomo e per questo è molto diffusa in cattività. L'anatra muta domestica, detta anatra muta di Barberia, si differenzia da quella selvatica soprattutto a livello morfologico, anche se pure per quanto riguarda la corporatura, la selvatica è sicuramente meno pesante della domestica. La varietà domestica è la tipica anatra muta bianca dal becco rosso.";

$titolo["atelopusvarius"] = "Rana pagliaccio";
$descrizione["atelopusvarius"] = "La rana pagliaccio, nome scientifico Atelopus varius, è una rana velenosa appartenente alla famiglia Bufonidae. In lingua inglese questo anfibio è conosciuto anche con il nome Variable Harlequin Frog ovvero rana arlecchino variabile. La rana pagliaccio è di piccole dimensioni, le sue misure vanno dai 2,4 cm ai 3,8 cm. Il corpo è sottile e la colorazione è molto variabile. La zona dorsale è di solito caratterizzata da un colore di fondo dato dalla sovrapposizione dei colori nero e marrone. Il dorso è poi ricoperto da macchie e striature che possono essere di diversi colori: rosso, arancio, giallo, blu o verde. Il ventre invece può essere di colore bianco, giallo o arancione. La loro pupilla è orizzontale ed ellittica.";

$titolo["bettasplendens"] = "Betta splendens";
$descrizione["bettasplendens"] = "Il pesce Betta splendens è un pesce d'acqua dolce appartenente alla famiglia Osphronemidae. Questa specie è diffusa nel Sud-est asiatico, nel territorio del bacino idrografico del fiume Mekong (Thailandia, Cambogia e Laos). Sono segnalate introduzioni accidentali negli ultimi decenni del XX secolo in Sudamerica (Brasile, Colombia, Repubblica Dominicana), Indonesia e Singapore Abita acque stagnanti, risaie, canali, specchi lacustri e aree fluviali con deboli correnti, sopportando acque poco ossigenate. Come tutte le specie della famiglia Osphronemidae è in grado di respirare ossigeno direttamente dall'aria, attraverso un organo chiamato labirinto.";

$titolo["clamidosauro"] = "Clamidosauro";
$descrizione["clamidosauro"] = "Il clamidosauro (Chlamydosaurus kingii) è un rettile carnivoro della famiglia Agamidae, diffuso nell'Australia settentrionale e in Nuova Guinea. È l'unica specie nota del genere Chlamydosaurus. La sua particolare denominazione deriva dal collare di circa 25 cm di diametro, chiamato 'clamide', del quale si serve per apparire più minaccioso di fronte a nemici, risolvere dispute territoriali, o durante il corteggiamento. Questo collare si caratterizza per un colorito molto vivo, vicino al rosso a causa dei numerosi vasi sanguigni che lo attraversano. Il colorito tuttavia può essere diverso, specialmente negli esemplari maschi, virando al giallo arancio, rosso o marrone. Il clamide di solito giace ripiegato contro la sua testa e il collo. L'arricciamento collo è supportato da lunghe spine di cartilagine che sono collegati alle ossa mascellari.";

$titolo["coccodrillodelnilo"] = "Coccodrillo del nilo";
$descrizione["coccodrillodelnilo"] = "Il coccodrillo del Nilo è il più grande e forte predatore africano d'acqua dolce. Quando giace immobile nell'acqua è impossibile individuarlo, finché non punta la sua preda e balza fuori dall'acqua. Il salto finale, con cui raggiunge la riva, può superare di molto la sua stessa lunghezza. La potenza e velocità del coccodrillo del Nilo sono incredibili: uccide grossi animali, trascinandoli in acqua e annegandoli. Il coccodrillo non può masticare, ma i suoi denti sono robusti e consentono all'animale di strappare grandi brandelli di carne dalla preda. I denti crescono in continuazione e vengono sostituiti da altri sempre nuovi.";

$titolo["coyote"] = "Coyote";
$descrizione["coyote"] = "Il coyote (Canis latrans), detto anche lupo della prateria, è un canide lupino indigeno del Nord America. In confronto al lupo grigio il coyote è di taglia più piccola e filogeneticamente più antico,paragonabile allo sciacallo dorato dell'Eurasia, benché ne sia più grande e con istinti più predatori. Viene classificato dalla IUCN tra le specie a rischio minimo, dato che ha un vastissimo areale che dal Nord America scende a includere il Messico e l'America centrale. È una specie molto adattabile, il cui areale si è ampliato in mezzo ai cambiamenti ambientali dell'uomo.";

$titolo["dingo"] = "Dingo";
$descrizione["dingo"] = "Il dingo (Canis lupus dingo) è un mammifero della famiglia dei canidi, introdotto dall'uomo in Australia. Presumibilmente la sua origine è asiatica. I primi resti fossili in Australia datano al 3500 a.C. e si ritiene di conseguenza che il dingo vi si sia stabilito in epoca precedente arrivando via mare insieme all'uomo. La morfologia del dingo non è cambiata nel corso di questi millenni, a riprova della mancanza di un allevamento selettivo da parte dell'uomo. Il dingo è strettamente imparentato con il cosiddetto cane canoro della Nuova Guinea: il loro lignaggio, originario dell'arcipelago malese, si staccò dalla linea che evolvette poi nel cane domestico.";

$titolo["emu"] = "Emù";
$descrizione["emu"] = "L'emù (Dromaius novaehollandiae) è un grande uccello appartenente alla famiglia Casuariidae, e rappresenta il secondo uccello vivente più alto al mondo dopo il suo parente ratite, lo struzzo. È endemico dell'Australia, dove è il più grande uccello autoctono e l'unico membro esistente del genere Dromaius. L'areale dell'emù comprende gran parte dell'Australia continentale, mentre le sottospecie insulari che abitavano le isole di Tasmania, Kangaroo Island e King Island si estinsero a seguito dell'insediamento dei coloni europei nelle isole nel 1788. Gli emù sono uccelli dalle piume morbide, marroni, dal lungo collo e zampe, che possono raggiungere fino a 1,9 metri di altezza. Come tutti i ratiti gli emù sono incapaci di volare, ma sono eccellenti corridori, e un emù in corsa può raggiungere anche i 48 km/h; si nutrono di una gran varietà di piante e insetti, e possono trascorrere intere settimane senza mangiare. Bevono di rado, assumendo la maggior parte dell'acqua dalle piante e dagli insetti di cui si nutrono, bevendo quanta più acqua possibile quando se ne presenta l'occasione.";

$titolo["faraonacrestata"] = "Faraona crestata";
$descrizione["faraonacrestata"] = "La faraona dal ciuffo (Guttera pucherani) , anche nota come faraona crestata o numida dal ciuffo, è un uccello della famiglia Numididae, diffusa nelle savane boscose, nelle boscaglie dell'Africa subsahariana. Si tratta di un uccello di taglia media, con una lunghezza totale di circa 50 centimetri (20 pollici), per un peso di 721-1543 grammi (1,590-3,402 libbre). Il piumaggio è primariamente nero con fitte macchie bianche. L'animale prende il nome dalla distintiva cresta di piume nere sulla sommità della testa, la cui forma varia da piccole penne ricce a un soffice piumino a seconda della sottospecie, e che la separa facilmente da tutte le altre specie di faraona, eccetto dalla faraona piumata (Guttera plumifera). I nomi 'crestato' e 'piumato' sono spesso applicati in modo errato nelle specie.";

$titolo["gekotokai"] = "Gekotokai";
$descrizione["gekotokai"] = "Il geco Tokay (Gekko gecko) è un grande sauro della famiglia Gekkonidae diffuso nel Sud-est asiatico. Il geco Tokay è il secondo geco più grande del mondo; solo Rhacodactylus leachianus lo supera in dimensioni. Il maschio è più grosso della femmina. Questa è lunga da 15 a 25 cm (con massime di 34-35), mentre il maschio misura da 20 a 33 cm (max 39-41). Il dimorfismo sessuale è accentuato, nella stagione degli amori, dai colori più sgargianti del maschio.";

$titolo["giraffareticolata"] = "Giraffa reticolata";
$descrizione["giraffareticolata"] = "La  giraffa somala o giraffa reticolata (Giraffa camelopardalis reticulata (de Winton, 1889)) è una sottospecie appartenente alla specie della giraffa settentrionale (Giraffa camelopardalis) originaria del Corno d'Africa, abitando la Somalia, l'Etiopia meridionale e il Kenya settentrionale. Ci sono circa 8.500 capi che vivono allo stato brado. La giraffa reticolata è stata descritta e ricevette il suo nome binomiale dallo zoologo britannico William Edward de Winton, nel 1899, tuttavia l'IUCN attualmente riconosce solo una specie di giraffa con nove sottospecie. La giraffa reticolata può incrociarsi con altre specie di giraffe in cattività o se entrano in contatto con popolazioni di specie diverse in natura. Insieme alla giraffa del Rothschild, è di gran lunga la giraffa più comune negli zoo. Il suo mantello è costituito da grandi macchie poligonali color marrone-arancione delineate da una rete di linee più chiare. Le macchie, talvolta, possono apparire di un rosso intenso e possono arrivare fino alle gambe. Le giraffe sono i mammiferi esistenti più alti al mondo."; 

$titolo["gruccionecomune"] = "Gruccione comune";
$descrizione["gruccionecomune"] = "Il gruccione comune (Merops apiaster) è un variopinto uccello appartenente alla famiglia Meropidae. È detto anche merope, come il genere (Merops) di cui fa parte. Come gli altri meropidi, è un uccello esile e multicolore. Può raggiungere una lunghezza di 26-29 cm, incluse le due penne allungate della coda, e la sua apertura alare può arrivare a 40 cm. Pesa fra 50 e 70 grammi. Il piumaggio variopinto, a grandi linee castano superiormente e azzurro inferiormente, è “dipinto” anche di giallo, verde, nero e arancione. La conformazione della coda è utile per il riconoscimento degli esemplari giovani rispetto ai gruccioni maturi: le penne della coda dei giovani sono di lunghezza simile, mentre gli adulti hanno penne timoniere centrali più lunghe. Il becco è nerastro, lungo e leggermente ricurvo verso il basso. Le zampe sono marrone-grigiastro. I sessi sono simili.";

$titolo["guppy"] = "Guppy";
$descrizione["guppy"] = "Il Guppy (Poecilia reticulata) è un pesce tropicale estremamente prolifico e facile da allevare. Si tratta di un pesce tropicale colorato ed esteticamente molto bello, che si adatta e sopravvive anche se, per inesperienza, si commette qualche piccolo errore. Oltre ad essere molto adattabile, questo adorabile amico di pinna si presenta declinato in tante varianti diverse, tutte da scoprire. Il Guppy è un pesce lungo tra i 3 e i 5 cm: di solito le femmine sono più grandi dei maschi e hanno una forma più arrotondata. All'interno di un acquario un Guppy può vivere fino a 5 anni. In natura, raramente supera i 2 anni.";

$titolo["iguanadaitubercoli"] = "Iguana dai tubercoli.";
$descrizione["iguanadaitubercoli"] = "L'iguana verde (Iguana iguana), detta anche iguana dai tubercoli o iguana comune, è un sauro arboricolo della famiglia Iguanidae, nativo del Centro e Sud America. È probabilmente la specie più grande della famiglia Iguanidae, sebbene alcune specie del genere Cyclura possano eguagliare o superarne il peso; presentano dimorfismo sessuale, e gli adulti tipicamente misurano da 120 a 170 cm di lunghezza dalla testa alla coda, ma alcuni maschi di grandi dimensioni possano superare 8 kg di peso, e raggiungere 2 m di lunghezza.";

$titolo["ippocampo"] = "Ippocampo";
$descrizione["ippocampo"] = "Hippocampus è un genere di pesci della famiglia Syngnathidae che comprende attualmente 54 specie di pesci d'acqua salata conosciuti comunemente come cavallucci marini o ippocampi, per via della testa che ricorda quella di un piccolo cavallo. Tutti i pesci del genere Hippocampus presentano le identiche caratteristiche fisiche e si distinguono dal resto dei pesci. Essi non nuotano all'indietro e la struttura fisica è incentrata su un asse verticale anziché orizzontale, quindi i cavallucci marini hanno posizione eretta, anche se durante il nuoto assumono una posizione più idrodinamica, avanzata. Un collo arcuato posiziona la testa in avanti, dalla caratteristica forma equina e con un muso allungato e tubolare. Le pinne pettorali (se presenti) sono posizionate come sempre dopo le aperture branchiali, ma la particolare forma fisica le fa somigliare più a delle orecchie equine.";

$titolo["leoneafricano"] = "Leone africano";
$descrizione["leoneafricano"] = "Il leone (Panthera leo), è un mammifero carnivoro della famiglia dei felidi. Dopo la tigre, è il più grande dei cinque grandi felidi del genere Panthera, con alcuni maschi la cui massa corporea supera i 250 kg. Il suo areale è, al 2011, ridotto quasi esclusivamente all'Africa subsahariana; il continuo impoverimento del suo habitat naturale e il protrarsi della caccia di frodo ai suoi danni ne fanno una specie vulnerabile, secondo la IUCN. La definizione è giustificata da un declino stimato tra il 30 e il 50% nella zona africana nei vent'anni precedenti. In virtù delle dimensioni e delle abitudini, questo felino non può essere allevato al di fuori di aree protette e parchi naturali o zoologici. Celebre è l'esempio della leonessa Elsa, restituita all'habitat naturale dopo avere vissuto per alcuni anni con i coniugi Adamson. Sebbene le cause del declino dei leoni non siano certe, il degrado dell'habitat e i conflitti con l'uomo ne sembrano le cause predominanti. Conosciuto come il 're della savana' o il 're degli animali', in natura un leone sopravvive da dieci a quindici anni, mentre in cattività può arrivare a venti. I maschi, in particolare, non superano spesso i dieci anni d'età in natura, in seguito agli infortuni derivanti dalle lotte con i rivali per il dominio sul branco";

$titolo["neolamprologus"] = "Neolamprologus";
$descrizione["neolamprologus"] = "Neolamprologus è un genere di pesci d'acqua dolce, appartenente alla famiglia Cichlidae, comprendente 50 specie. Il genere è endemico del lago Tanganica, le varie specie abitano le coste rocciose e sabbiose del lago. Tutte le specie presentano un corpo piuttosto allungato, più o meno compresso ai fianchi, con lunga pinna dorsale e una pinna caudale che può essere a mezzaluna, a delta oppure tondeggiante. La livrea varia considerevolmente secondo la specie: alcune presentano un colore giallo uniforme (N. leleupi), altre un fondo avorio fasciato e macchiato di bruno, fino al rosato tenue, altre specie hanno grosse fasce brune o nere";

$titolo["pescesanpietro"] = "Pesce San Pietro";
$descrizione["pescesanpietro"] = "Il pesce San Pietro (Zeus faber), è un pesce d'acqua salata, esponente della famiglia Zeidae. Il corpo è ellissoidale, alto e molto schiacciato sui lati. La bocca è grande e si può protrarre in avanti come un tubo. Gli occhi sono abbastanza grandi. La testa è dotata di numerose spine ed asperità. La pinna dorsale presenta 9-10 spine allungate e filiformi molto sviluppate, mentre la parte molle della pinna è posizionato simmetricamente alla pinna anale. Le pettorali sono di medie dimensioni, le ventrali piuttosto lunghe. La pinna caudale è ampia ed ha margine leggermente arrotondato, trasparente con raggi bianchi. Lungo l'inserzione delle pinne dorsale ed anale sono presenti piccole piastre ossee che portano spine. Sul margine ventrale è inoltre presente una carena di scaglie appuntite. La livrea ha un colore di fondo biancastro, grigiastro o giallastro screziato di beige e di bruno. Il ventre è bianco. Al centro del corpo un grosso ocello rotondeggiante nero, bordato di chiaro. I raggi dorsali sono bianchi e bruni, le ventrali grigiobrune. Le altre pinne sono trasparenti. Le dimensioni massime si attestano sui 90 cm di lunghezza per 8 kg di peso.";

$titolo["raganellapadana"] = "Raganella padana";
$descrizione["raganellapadana"] = "La raganella padana (Hyla perrini), è un anfibio della famiglia Hylidae, diffuso in Italia settentrionale, Svizzera e Slovenia. È una raganella di dimensioni medio-piccole, che raggiunge una lunghezza di 4-5 cm. È molto simile a Hyla arborea e Hyla intermedia: la colorazione delle parti superiori è spesso di colore verde brillante con un evidente striscia laterale di colore nero o marrone che dall'occhio raggiunge le zampe posteriori, a differenza delle altre specie la striatura di Hyla perrini è visibile solo ai lati, e non di fronte. Le parti inferiori sono generalmente bianco-giallastre. I maschi, come in tutte le specie di raganella presentano un sacco vocale sotto la gola. Le dita sono dotate di ventose che permettono all'animale di arrampicarsi sugli alberi.";

$titolo["ranafreccia"] = "Rana freccia";
$descrizione["ranafreccia"] = "La rana dorata o rana freccia (Phyllobates terribilis), è un piccolo anfibio anuro, vivacemente colorato, appartenente alla famiglia Dendrobatidae, diffuso nelle foreste pluviali delle Ande occidentali colombiane. Il suo aspetto viene considerato un classico esempio di aposematismo, essendo l'anfibio estremamente tossico. È ritenuto il più velenoso animale al mondo. La rana dorata è un anfibio di piccolissime dimensioni, sebbene P. terribilis sia considerato una delle più grandi specie della famiglia dei Dendrobatidae. C'è poco dimorfismo sessuale, ad eccezione di una leggera differenza di dimensioni: in media le femmine sono leggermente più grandi, come nella maggior parte degli anfibi anuri. Infatti i maschi adulti, con una lunghezza media di 45 mm, sono generalmente più piccoli delle femmine, la cui dimensione media è 47 mm. I maschi raggiungono la maturità sessuale quando raggiungono i 37 mm e le femmine a 40-41 mm. Come per tutti Dendrobatidae il corpo del Phyllobates terribilis adulto ha colori vivaci, ma non ha le macchie scure presenti su molte altre specie di questa famiglia.";

$titolo["ranamuta"]="Rana muta della Tazania";
$descrizione["ranamuta"]="Churamiti maridadi è uno dei leoni più rari del mondo, osservato sui monti Ukaguru solo un paio di volte negli ultimi decennie che potrebbe addirittura essere già estinto, almeno localmente. Nel 2019, Lawson e il suo team hanno organizzato una spedizione in Tanzania proprio alla ricerca di questo animale, il cui nome è in Swahili e significa 'splendida rana degli alberi'. La spedizione è stata un insuccesso totale, almeno da questo punto di vista; ma Lawson ha scoperto comunque qualcosa di nuovo. La nuova rana appartiene al genere Hyperolius, che comprende più di 200 specie distribuite in tutta l'Africa; tra queste ce ne sono alcune (poche, e quasi tutte in via d'estinzione) che hanno la gola ricoperta di piccole spine, e che, incidentalmente, sono mute. Hyperolius ukaguruensis va quindi ad aggiungersi a questo ristretto gruppo di rane che non usano i suoni per comunicare, ma qualcosa d'altro."; 

$titolo["riccioeuropeo"] = "Riccio europeo";
$descrizione["riccioeuropeo"] = "Il riccio comune, talvolta noto anche come riccio europeo (Erinaceus europaeus), è un mammifero della famiglia Erinaceidae, spesso impropriamente chiamato porcospino (che invece fa riferimento all'istrice). Il riccio presenta caratteristiche morfologiche arcaiche (come la formula dentaria e la conformazione del cervello) che lo accomunano ai primi mammiferi comparsi sulla Terra al termine del Cretaceo, rispetto ai quali non si è differenziato di molto: nel corso di milioni di anni ha solamente evoluto il caratteristico rivestimento di aculei. Il riccio presenta un cranio allungato e un piccolo cervello, la maggior parte del quale è addetto alla decodificazione dei segnali di natura olfattiva, rendendo l'olfatto il principale senso del riccio. Il naso è grosso, nero e assai mobile: i canali olfattivi sono costantemente umettati da una mucosa. Anche il senso del tatto è ben sviluppato; meno importante per il riccio è la vista; ciononostante, i ricci sono in grado di vedere fino a 30 m di distanza di giorno e 12 m di notte. Nonostante le piccole orecchie seminascoste dal pelo, i ricci sono in grado di udire frequenze comprese fra i 250 e i 60.000 Hz, quindi ben dentro gli ultrasuoni: ciò aiuta l'animale nella ricerca del cibo.";

$titolo["rospodellecanne"] = "Rospo delle canne";
$descrizione["rospodellecanne"] = "Il rospo delle canne (Rhinella marina), noto anche come rospo gigante neotropicale o rospo marino, è un grande rospo terrestre facente parte della famiglia Bufonidae, originario del Centro e Sud America, oltre a essere stato introdotto in varie isole dell'Oceania e dei Caraibi, e soprattutto nell'Australia settentrionale. Viene spesso inserito per limitare o eliminare la presenza di serpenti velenosi. Si tratta del rospo più grande al mondo, ed è membro del genere Rhinella, che comprende molte specie di veri rospi che si trovano in tutta l'America centrale e meridionale, sebbene fosse stato in precedenza assegnato al genere Bufo. Il rospo delle canne è una specie antica: un rospo fossile (l'esemplare UCMP 41159) facente parte della fauna di La Venta del Miocene superiore della Colombia, è risultato indistinguibile dai moderni rospi delle canne del Sud America settentrionale.";

$titolo["tartarugacaretta"] = "Tartaruga caretta";
$descrizione["tartarugacaretta"] = "La tartaruga comune o tartaruga caretta (Caretta caretta), è la tartaruga marina più comune del mar Mediterraneo. Fortemente minacciata in tutto il bacino del Mediterraneo, la specie è diffusa in molti mari del mondo: oltre che negli oceani Atlantico, Indiano e Pacifico, si può trovare nel mar Nero. Respira con il naso, con la bocca, e con un buco che si trova nella parte anteriore del corpo. Le tartarughe marine sono animali che si sono adattati alla vita acquatica grazie alla forma allungata del corpo ricoperto da un robusto guscio ed alla presenza di 4 zampe al posto delle pinne come un comune animale marino. Alla nascita è lunga circa 5 cm. La lunghezza di un esemplare adulto è di 80 – 140 cm, con massa variabile tra i 100 ed i 160 kg. La testa è grande, con il rostro molto incurvato. Gli arti sono molto sviluppati, specie gli anteriori, e muniti di due unghie negli individui giovani che si riducono ad una negli adulti. Ha un carapace di colore rosso marrone, striato di scuro nei giovani esemplari, e un piastrone giallastro, a forma di cuore, spesso con larghe macchie arancioni, dotato di due placche prefrontali ed un becco corneo molto robusto.";

$titolo["tigremalese"] = "Tigre malese";
$descrizione["tigremalese"] = "La tigre malese (Panthera tigris jacksoni), è una sottospecie di tigre, diffusa esclusivamente nella Penisola di Malacca. Morfologicamente molto simile alla tigre indocinese, la tigre malese ha un peso medio (riferito agli esemplari adulti) di circa 110 kg per i maschi e 90 kg per le femmine. La lunghezza dell'animale compresa la coda è nei maschi da 2,20 a 2,40 metri, mentre nelle femmine è da 2,10 a 2,20 metri. Le sue dimensioni fanno di questa sottospecie la più piccola di tutte le altre tigri.";

?>